package com.to52.dao.daoMapper;

import com.to52.dao.dataObject.ClientDO;
import org.springframework.stereotype.Repository;

@Repository
public interface ClientDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int insert(ClientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int insertSelective(ClientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    ClientDO selectByPrimaryKey(Integer cid);
    ClientDO selectByEmail(String email);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int updateByPrimaryKeySelective(ClientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int updateByPrimaryKey(ClientDO record);
}