package com.to52.dao.daoMapper;

import com.to52.dao.dataObject.OrderDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    int deleteByPrimaryKey(Integer oid);
    int deleteByBid(Integer bid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    OrderDO selectByPrimaryKey(Integer oid);
    List<OrderDO> selectByBid(Integer bid);
    OrderDO selectByTid(Integer tid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    int updateByPrimaryKey(OrderDO record);
}