package com.to52.dao.daoMapper;

import com.to52.dao.dataObject.TicketDO;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;
@Repository
public interface TicketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int insert(TicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int insertSelective(TicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    TicketDO selectByPrimaryKey(Integer tid);
    List<TicketDO> selectBySid(Integer sid);
    List<TicketDO> selectAll();
    List<TicketDO> selectByCondition(String destination, String departure, Date dateDepart,Date dateDepartTo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int updateByPrimaryKeySelective(TicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    int updateByPrimaryKey(TicketDO record);
}