package com.to52.dao.dataObject;

public class ClientDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.firstName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.lastName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.sex
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.email
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.phone
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.privilege
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cid
     *
     * @return the value of client.cid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cid
     *
     * @param cid the value for client.cid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.firstName
     *
     * @return the value of client.firstName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.firstName
     *
     * @param firstName the value for client.firstName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.lastName
     *
     * @return the value of client.lastName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.lastName
     *
     * @param lastName the value for client.lastName
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.sex
     *
     * @return the value of client.sex
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.sex
     *
     * @param sex the value for client.sex
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.email
     *
     * @return the value of client.email
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.email
     *
     * @param email the value for client.email
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.phone
     *
     * @return the value of client.phone
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.phone
     *
     * @param phone the value for client.phone
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password
     *
     * @return the value of client.password
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.privilege
     *
     * @return the value of client.privilege
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.privilege
     *
     * @param privilege the value for client.privilege
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }
}