package com.to52.dao.dataObject;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.dateOrder
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private Date dateOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.bid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ostate
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private Integer ostate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.dateOrder
     *
     * @return the value of order.dateOrder
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public Date getDateOrder() {
        return dateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.dateOrder
     *
     * @param dateOrder the value for order.dateOrder
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tid
     *
     * @return the value of order.tid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tid
     *
     * @param tid the value for order.tid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.bid
     *
     * @return the value of order.bid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.bid
     *
     * @param bid the value for order.bid
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ostate
     *
     * @return the value of order.ostate
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public Integer getOstate() {
        return ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ostate
     *
     * @param ostate the value for order.ostate
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setOstate(Integer ostate) {
        this.ostate = ostate;
    }
}