package com.to52.dao.dataObject;

import java.math.BigDecimal;
import java.util.Date;

public class TicketDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.tid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.sid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.state
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Integer tstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.destination
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.departure
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String departure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.dateDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Date dateDepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.dateArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Date dateArrival;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.timeDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Date timeDepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.timeArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private Date timeArrival;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.price
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seatNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String seatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.compartmentNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    private String compartmentNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.tid
     *
     * @return the value of ticket.tid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.reward
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    private BigDecimal reward;
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.tid
     *
     * @param tid the value for ticket.tid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.sid
     *
     * @return the value of ticket.sid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.sid
     *
     * @param sid the value for ticket.sid
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.state
     *
     * @return the value of ticket.state
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Integer getTstate() {
        return tstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.state
     *
     * @param tstate the value for ticket.state
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setTstate(Integer tstate) {
        this.tstate = tstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.destination
     *
     * @return the value of ticket.destination
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.destination
     *
     * @param destination the value for ticket.destination
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.departure
     *
     * @return the value of ticket.departure
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.departure
     *
     * @param departure the value for ticket.departure
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setDeparture(String departure) {
        this.departure = departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.dateDepart
     *
     * @return the value of ticket.dateDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Date getDateDepart() {
        return dateDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.dateDepart
     *
     * @param dateDepart the value for ticket.dateDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.dateArrival
     *
     * @return the value of ticket.dateArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Date getDateArrival() {
        return dateArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.dateArrival
     *
     * @param dateArrival the value for ticket.dateArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setDatearrival(Date dateArrival) {
        this.dateArrival = dateArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.timeDepart
     *
     * @return the value of ticket.timeDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Date getTimeDepart() {
        return timeDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.timeDepart
     *
     * @param timeDepart the value for ticket.timeDepart
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setTimedepart(Date timeDepart) {
        this.timeDepart = timeDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.timeArrival
     *
     * @return the value of ticket.timeArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public Date getTimeArrival() {
        return timeArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.timeArrival
     *
     * @param timeArrival the value for ticket.timeArrival
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setTimeArrival(Date timeArrival) {
        this.timeArrival = timeArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.price
     *
     * @return the value of ticket.price
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.price
     *
     * @param price the value for ticket.price
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seatNumber
     *
     * @return the value of ticket.seatNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seatNumber
     *
     * @param seatNumber the value for ticket.seatNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.compartmentNumber
     *
     * @return the value of ticket.compartmentNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public String getCompartmentNumber() {
        return compartmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.compartmentNumber
     *
     * @param compartmentNumber the value for ticket.compartmentNumber
     *
     * @mbg.generated Fri May 24 23:54:05 CEST 2019
     */
    public void setCompartmentNumber(String compartmentNumber) {
        this.compartmentNumber = compartmentNumber;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.reward
     *
     * @return the value of order.reward
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.reward
     *
     * @param reward the value for order.reward
     *
     * @mbg.generated Sat May 25 16:37:54 CEST 2019
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }
}